"""create column 'created_at'

Revision ID: 0552e9169781
Revises: 4d155f32f447
Create Date: 2026-02-15 18:48:50.148515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0552e9169781'
down_revision: Union[str, Sequence[str], None] = '4d155f32f447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_tasks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_tasks', 'created_at')
    # ### end Alembic commands ###
