"""add date row

Revision ID: 4da46c8f008a
Revises: 3969411dcc78
Create Date: 2026-03-02 20:34:52.106628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da46c8f008a'
down_revision: Union[str, Sequence[str], None] = '3969411dcc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('location', sa.String(), nullable=False))
    op.add_column('advertisements', sa.Column('date', sa.String(), nullable=False))
    op.drop_column('advertisements', 'location_and_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('location_and_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('advertisements', 'date')
    op.drop_column('advertisements', 'location')
    # ### end Alembic commands ###
