"""changes

Revision ID: 6be80549fe60
Revises: 4591c6fbe1f4
Create Date: 2026-03-14 18:37:42.889172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be80549fe60'
down_revision: Union[str, Sequence[str], None] = '4591c6fbe1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_tasks', sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_tasks', 'activated_at')
    # ### end Alembic commands ###
