"""changes

Revision ID: 6d844a270305
Revises: 9260813c47c8
Create Date: 2026-03-12 21:40:11.023469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d844a270305'
down_revision: Union[str, Sequence[str], None] = '9260813c47c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
