"""changes

Revision ID: 9260813c47c8
Revises: 5d9686585d1c
Create Date: 2026-03-12 21:22:39.304877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9260813c47c8'
down_revision: Union[str, Sequence[str], None] = '5d9686585d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_ads', sa.Column('advert_url', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'search_ads', ['advert_url'])
    op.drop_constraint(op.f('search_ads_ads_id_fkey'), 'search_ads', type_='foreignkey')
    op.create_foreign_key(None, 'search_ads', 'advertisements', ['advert_url'], ['advert_url'], ondelete='CASCADE')
    op.drop_column('search_ads', 'ads_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_ads', sa.Column('ads_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'search_ads', type_='foreignkey')
    op.create_foreign_key(op.f('search_ads_ads_id_fkey'), 'search_ads', 'advertisements', ['ads_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'search_ads', type_='unique')
    op.drop_column('search_ads', 'advert_url')
    # ### end Alembic commands ###
