"""changes

Revision ID: d7de5a898577
Revises: e50496ce62a5
Create Date: 2026-03-13 06:45:59.604833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7de5a898577'
down_revision: Union[str, Sequence[str], None] = 'e50496ce62a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('search_ads_advert_url_key'), 'search_ads', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('search_ads_advert_url_key'), 'search_ads', ['advert_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
