"""Add search table


Revision ID: e973a4aa8e1c
Revises: a408cd710c69
Create Date: 2026-02-09 19:57:01.522597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e973a4aa8e1c'
down_revision: Union[str, Sequence[str], None] = 'a408cd710c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('search_link', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ads_id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ads_id'], ['advertisements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['search_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('advertisements_advert_id_key'), 'advertisements', type_='unique')
    op.drop_column('advertisements', 'advert_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('advert_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('advertisements_advert_id_key'), 'advertisements', ['advert_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('search_ads')
    op.drop_table('search_tasks')
    # ### end Alembic commands ###
